name: Node.js CI

on:
  push:
    branches: [ main ]  # Garanta que está apontando para a branch correta
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.2'  # Especifique a versão do Node.js que seu projeto utiliza
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
